### ISSUE TITLE
Normalize IPv6 addresses in search

### ISSUE THREAD

**Issue by ghost** [zielmicha/fc00.org#13]
After lots of trial and error trying to search for my node, I've noticed the search can't handle IPv6 addresses with leftouts.

Expected this to work:
fc2b:c37e:e25c:4cae:4746:9ea5:8ccc:_dde_

Only this works:
fc2b:c37e:e25c:4cae:4746:9ea5:8ccc:_0dde_

**Comment by kylerchin** [comment]
I think I will do this.
