### ISSUE TITLE
h.fc00.org down

### ISSUE THREAD

**Issue by kyrias** [zielmicha/fc00.org#14]
The Hyperboria node that's supposed to run h.fc00.org seems to either be down, or not be peered with any others currently.

**Comment by zielmicha** [comment]
cjdroute process has crashed. I will investigate.

**Comment by zielmicha** [comment]
I've restarted it, though it's third time this process crashed. Is it normal for master branch of cjdelisle CJDNS?

**Comment by kyrias** [comment]
No, it's not. Could you get a backtrace/core dump?

**Comment by zielmicha** [comment]
I've pulled a new version and it appears to work now.
