### ISSUE TITLE
Enable DANE/TLSA for the domain

### ISSUE THREAD

**Issue by chpio** [zielmicha/fc00.org#16]
hi,

is there a possibility of enabling [DANE](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities) on the domain, so the dns response is secured (especially  h.fc00.org)?

**Comment by zielmicha** [comment]
Sorry, I believe that DNSSEC is a bad technology - I won't configure it on any domains I manage. I you want to be sure that you are talking to h.fc00.org, use its IPv6 address.
