### ISSUE TITLE
highlight of my node

### ISSUE THREAD

**Issue by whoizit** [zielmicha/fc00.org#2]
My opinion. It should highlight "my node" on map at the entrance to the site h.fc00.org. Like clicking on it. What do you think about it?

**Comment by kyrias** [comment]
The tricky part would be to reliably figure out the current node from the JS.

**Comment by chpio** [comment]
> The tricky part would be to reliably figure out the current node from the JS.

not really, the server knows the address already (it's shown on the page). the "tricky" part would be:

``` javascript
const html =
  `<script>
    var visitorIp = ${JSON.stringify(visitorIp)};
  </script>`;
```

**Comment by kyrias** [comment]
_If_ you're accessing it over hyperboria.

**Comment by chpio** [comment]
yeah, of course, but is it not enough?

**Comment by whoizit** [comment]
fix for me, btw
