### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by cwchristerw** [zielmicha/fc00.org#27]
Everyone can temporarily use my instance to browse map
Internet: https://hyperboria-map.cwo.fi/
HyperBoria: https://hyperboria-map.h.cwo.fi/
Yggdrasil Network: https://hyperboria-map.y.cwo.fi/

Service is provided by CWINFO&trade;

Same as #18

**Comment by cwchristerw** [comment]
Changes made to code #28 for making this code work on Docker instance

**Comment by zielmicha** [comment]
Fixed. (not sure what was the problem, the web server has just stopped)
