### ISSUE TITLE
links are not removed from the map

### ISSUE THREAD

**Issue by whoizit** [zielmicha/fc00.org#3]
I have node, http://h.fc00.org/#fc75:a699:c091:62a7:bae3:b1d8:1385:f55c
Earlier it was 14 nodes, but now it's only 7 nodes. I cut my conf 1-2 day ago, but map showing same.

**Comment by zielmicha** [comment]
Edge timeout is currently set to 3 weeks.

**Comment by whoizit** [comment]
Looks like fix for me, can close
